// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbAuwmr_CO3zyCvVZSU4ckW65Nm5GXBnE',
    appId: '1:796358783644:web:c5f811d75f8d608823f359',
    messagingSenderId: '796358783644',
    projectId: 'social-f6418',
    authDomain: 'social-f6418.firebaseapp.com',
    storageBucket: 'social-f6418.appspot.com',
    measurementId: 'G-P1JZ14P43N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY7UIkJ-2lrGqM8BN7XeJHy-ALnDBoa3w',
    appId: '1:796358783644:android:cab8434d75ae091423f359',
    messagingSenderId: '796358783644',
    projectId: 'social-f6418',
    storageBucket: 'social-f6418.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6drmYIw6mxui4Ik9UdLaH2FHQdNr0Z80',
    appId: '1:796358783644:ios:c7a93ff0b528f4f423f359',
    messagingSenderId: '796358783644',
    projectId: 'social-f6418',
    storageBucket: 'social-f6418.appspot.com',
    iosBundleId: 'com.example.social',
  );
}
